# Generated by Django 4.1.6 on 2024-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='homepage_sliders')),
                ('slider_link', models.CharField(max_length=200)),
                ('slider_description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Homepage Sliders',
            },
        ),
    ]
