# Generated by Django 4.1.6 on 2024-04-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0002_homepagesliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_event_1', models.CharField(max_length=200)),
                ('social_event_1_image', models.ImageField(blank=True, null=True, upload_to='Home_sections/SocialEvents_img')),
                ('social_event_1_description', models.TextField(max_length=200)),
                ('social_event_2', models.CharField(max_length=200)),
                ('social_event_2_image', models.ImageField(blank=True, null=True, upload_to='Home_sections/SocialEvents_img')),
                ('social_event_2_description', models.TextField(max_length=200)),
                ('social_event_3', models.CharField(max_length=200)),
                ('social_event_3_image', models.ImageField(blank=True, null=True, upload_to='Home_sections/SocialEvents_img')),
                ('social_event_3_description', models.TextField(max_length=200)),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='Home_sections/home_about')),
                ('about_description', models.TextField(max_length=200)),
                ('sermon_1', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Home sections',
            },
        ),
    ]
