# Generated by Django 4.1.6 on 2024-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0003_homesections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesections',
            name='sermon_1',
        ),
        migrations.AddField(
            model_name='homesections',
            name='sermon_1_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesections',
            name='sermon_2_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesections',
            name='sermon_3_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='about_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_1_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_2_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_3_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
