# Generated by Django 4.1.6 on 2024-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0004_remove_homesections_sermon_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='core_value_1_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='core_value_2_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='core_value_3_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='core_value_4_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='department_1_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='department_2_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='department_3_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='page_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagesliders',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_1_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_2_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homesections',
            name='social_event_3_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
