# Generated by Django 4.1.6 on 2024-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0006_events_gallery_sermons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='category',
            field=models.CharField(choices=[('podcast', 'podcast'), ('celebration', 'celebration'), ('discipleship', 'discipleship'), ('children', 'children')], default='unlabled', max_length=200),
        ),
    ]
