# Generated by Django 4.1.6 on 2024-07-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0007_sermons_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
