# Generated by Django 3.2.1 on 2024-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfm', '0008_sermons_link_alter_sermons_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesections',
            name='sermon_1_link',
        ),
        migrations.RemoveField(
            model_name='homesections',
            name='sermon_2_link',
        ),
        migrations.RemoveField(
            model_name='homesections',
            name='sermon_3_link',
        ),
        migrations.AlterField(
            model_name='homesections',
            name='about_description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
