databases:
  - name: cfmDB
    plan: free
    databaseName: cfmdb
    user: cfmdb_user

services:
  - type: web
    plan: free
    name: cfm
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn christ_fullness.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cfmdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4